# Generated by Django 5.1.3 on 2024-12-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stresstrack', '0003_alter_course_students_alter_course_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Opción múltiple'), ('scale', 'Escala')], default='multiple_choice', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='studentresponse',
            unique_together={('student', 'stress_test')},
        ),
    ]
