# Generated by Django 5.1.3 on 2024-12-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stresstrack', '0004_question_question_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='responsedetail',
            name='selected_option',
            field=models.CharField(choices=[(1, 'Nunca'), (2, 'Rara vez'), (3, 'A veces'), (4, 'Casi siempre'), (5, 'Siempre')], max_length=15),
        ),
    ]
